using Entities.Models.Content;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Repository.Configurations;

public class SiteSettingConfiguration : IEntityTypeConfiguration<SiteSetting>
{
    public void Configure(EntityTypeBuilder<SiteSetting> builder)
    {
        builder.HasData(
            new SiteSetting { Id = 1, Key = "home.hero.tagline", Value = "Where Excellence" },
            new SiteSetting { Id = 2, Key = "home.hero.taglineGold", Value = "Meets Tomorrow" },
            new SiteSetting { Id = 3, Key = "home.hero.subtitle", Value = "Premium private education in the heart of Kirinyaga. 2,000+ learners, 120+ expert educators — academics, sports, music, and performing arts under one roof." },
            new SiteSetting { Id = 4, Key = "home.hero.directorName", Value = "Mr. Albert Njeru" },
            new SiteSetting { Id = 5, Key = "home.hero.directorTitle", Value = "Founder & Director" },
            new SiteSetting { Id = 6, Key = "home.hero.directorCredential", Value = "M.Ed., UoN" },
            new SiteSetting { Id = 7, Key = "home.hero.directorQuote", Value = "Every child in Kirinyaga deserves an education that changes the trajectory of a family for generations. That is the promise we keep, every single day." },
            new SiteSetting { Id = 8, Key = "home.stats.0.label", Value = "Students" },
            new SiteSetting { Id = 9, Key = "home.stats.0.value", Value = "2,000+" },
            new SiteSetting { Id = 10, Key = "home.stats.1.label", Value = "Educators" },
            new SiteSetting { Id = 11, Key = "home.stats.1.value", Value = "120+" },
            new SiteSetting { Id = 12, Key = "home.stats.2.label", Value = "School Buses" },
            new SiteSetting { Id = 13, Key = "home.stats.2.value", Value = "8" },
            new SiteSetting { Id = 14, Key = "home.stats.3.label", Value = "Sports Codes" },
            new SiteSetting { Id = 15, Key = "home.stats.3.value", Value = "12" },
            new SiteSetting { Id = 16, Key = "home.testimonials.0.name", Value = "Grace Njeri" },
            new SiteSetting { Id = 17, Key = "home.testimonials.0.role", Value = "Parent · Grade 5" },
            new SiteSetting { Id = 18, Key = "home.testimonials.0.quote", Value = "Alber School has transformed my daughter completely. The teaching quality is unmatched anywhere in Kirinyaga County." },
            new SiteSetting { Id = 19, Key = "home.testimonials.1.name", Value = "Brian Mutua" },
            new SiteSetting { Id = 20, Key = "home.testimonials.1.role", Value = "Student · Grade 9" },
            new SiteSetting { Id = 21, Key = "home.testimonials.1.quote", Value = "The sports facilities here are world-class. I have grown as both an athlete and a leader since joining Alber." },
            new SiteSetting { Id = 22, Key = "home.testimonials.2.name", Value = "Dr. Samuel Kariuki" },
            new SiteSetting { Id = 23, Key = "home.testimonials.2.role", Value = "Parent · PP2 & Grade 7" },
            new SiteSetting { Id = 24, Key = "home.testimonials.2.quote", Value = "Both my children attend Alber. From Playgroup all the way to Senior School — the continuity and quality are simply unmatched in Kirinyaga." },
            new SiteSetting { Id = 25, Key = "home.testimonials.3.name", Value = "Amina Ochieng" },
            new SiteSetting { Id = 26, Key = "home.testimonials.3.role", Value = "Student · Music Academy" },
            new SiteSetting { Id = 27, Key = "home.testimonials.3.quote", Value = "I performed my first piano recital here in Grade 5. The music teachers are genuinely world-class professionals." },
            new SiteSetting { Id = 28, Key = "about.mission", Value = "To cultivate visionary leaders through innovative, competency-based education that honours Kenyan heritage while embracing global excellence. We nurture every learner's genius — academically, artistically, and athletically." },
            new SiteSetting { Id = 29, Key = "about.vision", Value = "To be East Africa's most sought-after private institution — where every learner discovers their genius in world-class facilities, guided by expert educators who inspire curiosity and ambition in equal measure." },
            new SiteSetting { Id = 30, Key = "about.history.0.year", Value = "2005" },
            new SiteSetting { Id = 31, Key = "about.history.0.title", Value = "Foundation" },
            new SiteSetting { Id = 32, Key = "about.history.0.desc", Value = "Alber School established in Kutus, Kirinyaga County, with a bold vision to deliver premium education adjacent to the Governor's Offices." },
            new SiteSetting { Id = 33, Key = "about.history.1.year", Value = "2010" },
            new SiteSetting { Id = 34, Key = "about.history.1.title", Value = "Primary Expansion" },
            new SiteSetting { Id = 35, Key = "about.history.1.desc", Value = "Full primary school opened with 400 students. CBC-aligned curriculum launched alongside dedicated science laboratories." },
            new SiteSetting { Id = 36, Key = "about.history.2.year", Value = "2014" },
            new SiteSetting { Id = 37, Key = "about.history.2.title", Value = "Arts Academy" },
            new SiteSetting { Id = 38, Key = "about.history.2.desc", Value = "Music studios, drama theatre, and dance halls launched — the first dedicated performing arts complex in Kirinyaga County." },
            new SiteSetting { Id = 39, Key = "about.history.3.year", Value = "2018" },
            new SiteSetting { Id = 40, Key = "about.history.3.title", Value = "IGCSE Pathway" },
            new SiteSetting { Id = 41, Key = "about.history.3.desc", Value = "Cambridge international curriculum introduced, giving students a globally recognised academic pathway from Grade 10." },
            new SiteSetting { Id = 42, Key = "about.history.4.year", Value = "2022" },
            new SiteSetting { Id = 43, Key = "about.history.4.title", Value = "Sports Complex" },
            new SiteSetting { Id = 44, Key = "about.history.4.desc", Value = "New sports complex completed — football pitch, basketball courts, swimming pool, and athletics track." },
            new SiteSetting { Id = 45, Key = "about.history.5.year", Value = "2026" },
            new SiteSetting { Id = 46, Key = "about.history.5.title", Value = "Digital Frontier" },
            new SiteSetting { Id = 47, Key = "about.history.5.desc", Value = "360° virtual tours, smart classrooms, and digital learning platforms launched. 2,000+ students, 120+ staff." },
            new SiteSetting { Id = 48, Key = "about.values.0.icon", Value = "🎓" },
            new SiteSetting { Id = 49, Key = "about.values.0.title", Value = "Academic Excellence" },
            new SiteSetting { Id = 50, Key = "about.values.0.desc", Value = "Rigorous standards across CBC and Cambridge IGCSE frameworks with continuous assessment." },
            new SiteSetting { Id = 51, Key = "about.values.1.icon", Value = "🤝" },
            new SiteSetting { Id = 52, Key = "about.values.1.title", Value = "Integrity" },
            new SiteSetting { Id = 53, Key = "about.values.1.desc", Value = "Honesty and ethical conduct are the foundation of every interaction in our community." },
            new SiteSetting { Id = 54, Key = "about.values.2.icon", Value = "🌍" },
            new SiteSetting { Id = 55, Key = "about.values.2.title", Value = "Global Citizenship" },
            new SiteSetting { Id = 56, Key = "about.values.2.desc", Value = "Celebrating Kenyan heritage while preparing learners for a connected, diverse world." },
            new SiteSetting { Id = 57, Key = "about.values.3.icon", Value = "💡" },
            new SiteSetting { Id = 58, Key = "about.values.3.title", Value = "Innovation" },
            new SiteSetting { Id = 59, Key = "about.values.3.desc", Value = "Encouraging curiosity, creativity, and problem-solving across all disciplines." },
            new SiteSetting { Id = 60, Key = "about.values.4.icon", Value = "🏆" },
            new SiteSetting { Id = 61, Key = "about.values.4.title", Value = "Holistic Growth" },
            new SiteSetting { Id = 62, Key = "about.values.4.desc", Value = "Developing the whole child — academically, physically, artistically, and emotionally." },
            new SiteSetting { Id = 63, Key = "about.values.5.icon", Value = "🌱" },
            new SiteSetting { Id = 64, Key = "about.values.5.title", Value = "Sustainability" },
            new SiteSetting { Id = 65, Key = "about.values.5.desc", Value = "Stewardship of our community and environment for future generations." },
            new SiteSetting { Id = 66, Key = "about.leadership.0.name", Value = "Dr. Wanjiku Mwangi" },
            new SiteSetting { Id = 67, Key = "about.leadership.0.title", Value = "Head Teacher" },
            new SiteSetting { Id = 68, Key = "about.leadership.0.img", Value = "https://i.pravatar.cc/400?img=47" },
            new SiteSetting { Id = 69, Key = "about.leadership.0.bio", Value = "PhD in Educational Leadership, University of Nairobi. 25 years in education. Champion of CBC implementation in Kirinyaga." },
            new SiteSetting { Id = 70, Key = "about.leadership.1.name", Value = "Mr. Peter Kamau" },
            new SiteSetting { Id = 71, Key = "about.leadership.1.title", Value = "Deputy Head Teacher" },
            new SiteSetting { Id = 72, Key = "about.leadership.1.img", Value = "https://i.pravatar.cc/400?img=11" },
            new SiteSetting { Id = 73, Key = "about.leadership.1.bio", Value = "M.Ed Kenyatta University. Specialises in curriculum development and teacher professional growth." },
            new SiteSetting { Id = 74, Key = "about.leadership.2.name", Value = "Ms. Eunice Achieng" },
            new SiteSetting { Id = 75, Key = "about.leadership.2.title", Value = "Director of Academics" },
            new SiteSetting { Id = 76, Key = "about.leadership.2.img", Value = "https://i.pravatar.cc/400?img=48" },
            new SiteSetting { Id = 77, Key = "about.leadership.2.bio", Value = "Cambridge-certified IGCSE coordinator. Oversees all academic pathways from PP1 through Grade 12." },
            new SiteSetting { Id = 78, Key = "about.leadership.3.name", Value = "Mr. Francis Omondi" },
            new SiteSetting { Id = 79, Key = "about.leadership.3.title", Value = "Director of Co-Curricular" },
            new SiteSetting { Id = 80, Key = "about.leadership.3.img", Value = "https://i.pravatar.cc/400?img=15" },
            new SiteSetting { Id = 81, Key = "about.leadership.3.bio", Value = "Former national athlete. Leads sports, music, drama, and all co-curricular programmes across the school." },
            new SiteSetting { Id = 82, Key = "programs.cbcFramework", Value = "Competency-based assessment\nLearner-centered projects\nNational values integration\nCareer pathways from Grade 7\nContinuous assessment portfolios" },
            new SiteSetting { Id = 83, Key = "programs.igcseFramework", Value = "Cambridge international standards\nIGCSE & A-Level examinations\nGlobal university recognition\nRigorous external assessment\nCross-cultural curriculum breadth" }
        );
    }
}